name: satellite-ellipticities
dependencies:
- python=3.9
- ipykernel
- numpy
- astropy
- pandas
- seaborn
- pyarrow
- pip
- pip:
  - git+https://github.com/sagasurvey/saga.git
  - git+https://github.com/yymao/fast3tree.git