name: satellite-ellipticities
channels:
  - conda-forge
dependencies:
  - python=3.9
  - ipykernel
  - numpy
  - astropy
  - dotenv
  - pandas
  - seaborn
  - pyarrow
  - fast3tree
  - pip
  - pip:
    - git+https://github.com/sagasurvey/saga.git